# Generated by rust2rpm 13
# * assert_cmd is not packaged
%bcond_with check
%global __cargo_skip_build 0

%global crate bat

Name:           rust-%{crate}
Version:        0.22.1
Release:        1%{?dist}
Summary:        cat(1) clone with wings

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/bat
Source:         %{crates_source}
# Initial patched metadata
# * Bump console to 0.9, https://github.com/sharkdp/bat/pull/657
# * Bump git2 to 0.11, https://github.com/sharkdp/bat/commit/826624c9fa3af2b9aacd2bbdaa03304b9376b832
Patch0:         bat-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Cat(1) clone with wings.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{_bindir}/bat
%doc %{_mandir}/man1/bat.1*

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
install -Dpm0644 -t %{buildroot}%{_mandir}/man1 \
  doc/bat.1

%if %{with check}
%check
%cargo_test
%endif
